---
abstract: 'Extensive, yet simple, logging role using Log::Dispatchouli'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Mouse: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-Role-Loggable
no_index:
  file:
    - README.pod
requires:
  Carp: 0
  Log::Dispatchouli: 0
  Mouse: 1.04
  Mouse::Role: 0
  Mouse::Util::TypeConstraints: 0
  MouseX::Types: 0.06
  MouseX::Types::Mouse: 0
  Safe::Isa: 0
  namespace::sweep: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/schwern/Mousex-Role-Loggable/issues
  repository: http://github.com/schwern/MouseX-Role-Loggable
version: 0.112
